# Generated by Django 3.0.14 on 2021-04-20 13:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='status',
            field=models.CharField(choices=[('o', 'Do'), ('i', 'Doing'), ('t', 'Testing'), ('d', 'Done')], max_length=1),
        ),
        migrations.AlterField(
            model_name='commenttask',
            name='time',
            field=models.FloatField(verbose_name='Time complete'),
        ),
        migrations.AlterField(
            model_name='project',
            name='release_date',
            field=models.DateField(verbose_name='Finish'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(verbose_name='Start'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('p', 'Planned'), ('d', 'Doing'), ('t', 'Testing'), ('r', 'Release')], max_length=1),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name of project'),
        ),
        migrations.AlterField(
            model_name='task',
            name='release_datetime',
            field=models.DateTimeField(verbose_name='Finish task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='start_datetime',
            field=models.DateTimeField(verbose_name='Start task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('o', 'Do'), ('i', 'Doing'), ('t', 'Testing'), ('d', 'Done')], max_length=1),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Name of task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='total_time',
            field=models.FloatField(verbose_name='Total time complete'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to=settings.AUTH_USER_MODEL, verbose_name='Appointed by'),
        ),
    ]
