# Generated by Django 3.0.14 on 2021-05-02 14:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0002_auto_20210420_1619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to=settings.AUTH_USER_MODEL, verbose_name='Appointed by'),
        ),
    ]
