# Generated by Django 3.0.14 on 2021-05-14 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
        ('project', '0003_auto_20210502_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commenttask',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_task', to='user_profile.UserProfile', verbose_name='Appointed by'),
        ),
        migrations.AlterField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='user_profile.UserProfile', verbose_name='Appointed by'),
        ),
    ]
